<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AuToColaB</title>
    <link rel="stylesheet" href="style.css" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>
  <body>
    <header>
      <div class="container">
        <div id="branding">
          <h1>AuTo<span class="highlight">ColaB</span></h1>
        </div>
        <nav>
          <ul>
            <li class="current"><a href="index.html">Cauta</a></li>
            <li><a href="favorite.html">Favorite</a></li>
            <li><a href="autentificare.html">Autentificare</a></li>
            <li><a href="inregistrare.html">Inregistrare</a></li>
          </ul>
          <img src="avatar1.jpg" />
        </nav>
      </div>
    </header>
    <div class="categories">
      <div class="small-container">
        <div class="row">
          <div class="col-3">
            <form class="masini" action="/action_page.php">
              <label for="cars">Marca:</label>
              <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat" selected>Fiat</option>
                <option value="audi">Audi</option>
              </select>
            </form>
          </div>
          <div class="col-3">
            <form action="/action_page.php">
              <label for="cars">Model:</label>
              <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat" selected>Fiat</option>
                <option value="audi">Audi</option>
              </select>
            </form>
          </div>
          <div class="col-3">
            <form action="/action_page.php">
              <label for="cars">Pret de la:</label>
              <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat" selected>Fiat</option>
                <option value="audi">Audi</option>
              </select>
            </form>
          </div>
          <div class="col-3">
            <form action="/action_page.php">
              <label for="cars">Pret pana la:</label>
              <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat" selected>Fiat</option>
                <option value="audi">Audi</option>
              </select>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="categories">
      <div class="small-container">
        <div class="row">
          <div class="col-3">
            <form action="/action_page.php">
              <label for="cars">Km de la:</label>
              <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat" selected>Fiat</option>
                <option value="audi">Audi</option>
              </select>
            </form>
          </div>
          <div class="col-3">
            <form action="/action_page.php">
              <label for="cars">Km pana la:</label>
              <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat" selected>Fiat</option>
                <option value="audi">Audi</option>
              </select>
            </form>
          </div>
          <div class="col-3">
            <form action="/action_page.php">
              <label for="cars">Tara Origine:</label>
              <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat" selected>Fiat</option>
                <option value="audi">Audi</option>
              </select>
            </form>
          </div>
          <div class="col-3">
            <form action="/action_page.php">
              <label for="cars">Combustibil:</label>
              <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat" selected>Fiat</option>
                <option value="audi">Audi</option>
              </select>
            </form>
          </div>
        </div>
      </div>
    </div>
    <section id="newsletter">
      <div class="container">
        <form>
          <input type="email" placeholder=" " />
          <button type="submit" class="button_1">Cauta</button>
        </form>
      </div>
    </section>
    <div class="anunturi">
      <div class="un_anunt">
        <img src="car1.jpg" />

        <div class="date">
          <h1><a href=" ">Dacia Solenza</a></h1>
          <p>2005 - 128 000 km - Benzina - 400 cm3</p>
          <p2>Braila - Romania</p2>
          <br />
          <h2>4000 lei</h2>
          <br />
          <p3
            >Adauga la favorite<button
              id="btn"
              class="heart fa fa-heart-o"
            ></button
          ></p3>
        </div>
      </div>
      <div class="un_anunt">
        <img src="car2.jpg" />

        <div class="date">
          <h1><a href=" ">Dacia Solenza</a></h1>
          <p>2005 - 128 000 km - Benzina - 400 cm3</p>
          <p2>Braila - Romania</p2>
          <br />
          <h2>4000 lei</h2>
          <br />
          <p3
            >Adauga la favorite<button
              id="btn"
              class="heart fa fa-heart-o"
            ></button
          ></p3>
        </div>
      </div>
      <div class="un_anunt">
        <img src="car3.jpg" />

        <div class="date">
          <h1><a href=" ">Dacia Solenza</a></h1>
          <p>2005 - 128 000 km - Benzina - 400 cm3</p>
          <p2>Braila - Romania</p2>
          <br />
          <h2>4000 lei</h2>
          <br />
          <p3
            >Adauga la favorite<button
              id="btn"
              class="heart fa fa-heart-o"
            ></button
          ></p3>
        </div>
      </div>
      <div class="un_anunt">
        <img src="car4.jpg" />

        <div class="date">
          <h1><a href=" ">Dacia Solenza</a></h1>
          <p>2005 - 128 000 km - Benzina - 400 cm3</p>
          <p2>Braila - Romania</p2>
          <br />
          <h2>4000 lei</h2>
          <br />
          <p3
            >Adauga la favorite<button
              id="btn"
              class="heart fa fa-heart-o"
            ></button
          ></p3>
        </div>
      </div>
    </div>

    <!----------footer------------>
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="footer-col-1">
            <h3>Download our apps</h3>
            <p>Download App for Android and IOS mobile phone</p>
            <div class="app-logo">
              <img src="play-store.png" />
              <img src="app-store.png" />
            </div>
          </div>
          <div class="footer-col-2">
            <p>
              It is a long established fact that a reader will be distracted by
              the readable content of a page when looking at its layout.
            </p>
          </div>
          <div class="footer-col-3">
            <h3>Useful Links</h3>
            <ul>
              <li>Coupons</li>
              <li>Blog post</li>
              <li>Return Policy</li>
              <li>Join Affiliate</li>
            </ul>
          </div>
          <div class="footer-col-3">
            <h3>Follow us</h3>
            <ul>
              <li>Facebook</li>
              <li>Twitter</li>
              <li>Instagram</li>
              <li>YouTube</li>
            </ul>
          </div>
        </div>
        <hr />
        <p class="copyright">Copyright 2020 - Easy site cu Mihai</p>
      </div>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
      integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
      crossorigin="anonymous"
    ></script>
    <script src="js.js" defer></script>
  </body>
</html>
